version: "3.6"

services:
  ocr-service:
    container_name: ocr-service
    platform: linux
    build: .
    restart: always
    environment:
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$no_proxy
    ports:
      - "8090:8090"
    expose: 
      - "8090"
