version: "3.7"

services:
  ocr-service:
    platform: linux
    build: .
    restart: always
    environment:
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$no_proxy
    ports:
      - "${OCR_SERVICE_OUTPUT_PORT:-8090}:8090"

