version: "3.7"

services:
  ocr-service:
    container_name: ocr-service
    platform: linux
    build: .
    restart: always
    mem_swappiness: 0
    shm_size : 1024mb
    privileged: true
    security_opt:
      - seccomp:unconfined
    environment:
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$no_proxy
      - OMP_THREAD_LIMIT=1
      #- OMP_NUM_THREADS=1
      #- OMP_DYNAMIC=TRUE
      #- OMP_NESTED=TRUE
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 262144
    ports:
      - "8090:8090"
    expose: 
      - "8090"
