from __future__ import annotations

import logging
import time
import traceback
from multiprocessing.dummy import Pool, Queue

from tesserocr import PyTessBaseAPI

from config import CPU_THREADS, TESSDATA_PREFIX, TESSERACT_LANGUAGE, TESSERACT_TIMEOUT
from ocr_service.dto.process_context import ProcessContext


class OcrEngine:
    def __init__(self, log: logging.Logger) -> None:
        self.log = log

    def _init_tesseract_api_worker(self) -> PyTessBaseAPI:
        tess_api = PyTessBaseAPI(path=TESSDATA_PREFIX, lang=TESSERACT_LANGUAGE)  # type: ignore
        self.log.debug("Initialised pytesseract api worker for language:" + str(TESSERACT_LANGUAGE))
        return tess_api

    def _process_image(self, img, img_id: int, tess_api: PyTessBaseAPI) -> tuple[str, int, dict]:
        tess_api.SetImage(img)
        output_str = tess_api.GetUTF8Text()

        tess_data = {}
        confidences = tess_api.AllWordConfidences()
        len_confidence = 1 if len(confidences) == 0 else len(confidences)
        tess_data["confidence"] = sum(confidences)/len_confidence

        self.log.info("finished processing img: " + str(img_id))

        return output_str, img_id, tess_data

    def run(self, ctx: ProcessContext) -> None:
        image_count = len(ctx.images)
        tess_data = []

        if image_count == 0:
            return

        self.log.info("A total of " + str(image_count) + " images have been generated from " + ctx.file_name)
        ocr_start_time = time.time()
        proc_results = list()

        with Pool(processes=CPU_THREADS) as process_pool:
            tess_api_q: Queue = Queue()
            for count, img in enumerate(ctx.images):
                tess_api_q.put(self._init_tesseract_api_worker())
                proc_results.append(process_pool.starmap_async(self._process_image,
                                                               [(img, count, tess_api_q.get(),)],
                                                               chunksize=1,
                                                               error_callback=logging.error))
            try:
                for result in proc_results:
                    result_data = result.get(timeout=TESSERACT_TIMEOUT)
                    _output_text, _, _tess_data = result_data[0][0], result_data[0][1], result_data[0][2]
                    ctx.output_text += str(_output_text)
                    tess_data.append(_tess_data)
            except Exception as worker_exception:
                raise Exception("OCR exception generated by worker: "
                                + str(traceback.format_exc())) from worker_exception
            finally:
                for tess_api in tess_api_q.queue:
                    tess_api.End()

        ocr_end_time = time.time()

        self.log.info(f"OCR processing finished | Elapsed : {ocr_end_time - ocr_start_time:.4f} seconds")

        ctx.metadata["pages"] = image_count
        ctx.metadata["confidence"] = round(sum([page["confidence"] for page in tess_data]) / image_count, 4)
